name: klikrental

services:
  # --- SERVICE DATABASE (MYSQL) ---
  db:
    image: mysql:8.0
    container_name: klikrental_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-klikrental}
      MYSQL_USER: ${DB_USERNAME:-sail}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - klikrental_net

  # --- SERVICE LARAVEL APP (PHP-FPM 8.4 + NODEJS) ---
  app:
    build: .
    container_name: klikrental_app
    restart: always
    volumes: 
      - .:/var/www
    networks:
      - klikrental_net

  # --- SERVICE NGINX (WEBSERVER) ---
  nginx:
    image: nginx:latest
    container_name: klikrental_nginx
    restart: always
    ports:
      - "4050:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - klikrental_net

# --- KONFIGURASI NETWORK ---
networks:
  klikrental_net:
    driver: bridge

# --- PERSISTENT STORAGE ---
volumes:
  db_data:

# --- METADATA CASAOS ---
x-casaos:
  author: self
  category: Web App
  hostname: ""
  icon:
  index: /
  is_uncontrolled: false
  port_map: "8080"
  scheme: http
  title:
    custom: Klikrental